import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Button, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import axios from "axios";
import { apiClient } from "../../api/client";
import { PageFrame } from "../../pages/PageFrame";
type Address = { id: string; label?: string; street: string; city: string; isDefault: boolean }; type Order = { id: string; orderNumber?: string; status: string; paymentStatus: string; total?: number; createdAt: string };
const text = (e: unknown) => axios.isAxiosError(e) ? e.response?.data?.message ?? "Request failed" : "Request failed";
export function OrdersPage() { const qc = useQueryClient(); const [addressId, setAddressId] = useState(""); const [error, setError] = useState<string | null>(null); const addresses = useQuery({ queryKey: ["addresses"], queryFn: async () => (await apiClient.get<{ data: Address[] }>("/addresses")).data.data }); const orders = useQuery({ queryKey: ["orders"], queryFn: async () => (await apiClient.get<{ data: Order[] }>("/orders/my")).data.data }); const checkout = useMutation({ mutationFn: () => apiClient.post("/orders", { addressId }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["orders"] }); qc.invalidateQueries({ queryKey: ["cart"] }); }, onError: e => setError(text(e)) }); const cancel = useMutation({ mutationFn: (id: string) => apiClient.patch(`/orders/${id}/cancel`), onSuccess: () => qc.invalidateQueries({ queryKey: ["orders"] }), onError: e => setError(text(e)) }); return <PageFrame><Stack spacing={3}><Typography component="h1" variant="h4">Checkout and orders</Typography><Paper variant="outlined" sx={{ p: 2 }}><Stack spacing={2}><Typography>Place an order from your current cart.</Typography><TextField select label="Delivery address" value={addressId} onChange={e => setAddressId(e.target.value)}>{addresses.data?.map(a => <MenuItem key={a.id} value={a.id}>{a.label ?? "Address"} — {a.street}, {a.city} {a.isDefault ? "(Default)" : ""}</MenuItem>)}</TextField><Button variant="contained" disabled={!addressId || checkout.isPending} onClick={() => checkout.mutate()}>Checkout cart</Button></Stack></Paper>{orders.data?.map(order => <Paper key={order.id} variant="outlined" sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between"><Typography>{order.orderNumber ?? order.id} · {order.status} · {order.paymentStatus} · KES {order.total ?? "—"}</Typography><Button color="error" disabled={cancel.isPending || ["CANCELLED", "DELIVERED"].includes(order.status)} onClick={() => cancel.mutate(order.id)}>Cancel</Button></Stack></Paper>)}{error && <Alert severity="error">{error}</Alert>}</Stack></PageFrame>; }
