export const ROUTES = {
  landing: "/",
  webLogin: "/login",
  webRegister: "/register",
  customerDashboard: "/products",
  customerCart: "/cart",
  checkout: "/checkout",
  orderConfirmation: "/order-confirmation",
  customerAddresses: "/profile/addresses",
  customerOrders: "/orders",
  orders: "/orders",
  customerOutfits: "/profile/outfits",
  categories: "/categories",
  brands: "/brands",
  wishlist: "/wishlist",
  profile: "/profile",
  aiStylist: "/ai-stylist",
  outfitBuilder: "/outfit-builder",
  accessDenied: "/studio/access-denied",
} as const;

export const STUDIO_ROUTES = {
  root: "/studio",
  login: "/studio/login",
  register: "/studio/register",
  customerDashboard: "/studio/customer",
  customerCart: "/studio/customer/cart",
  customerAddresses: "/studio/customer/addresses",
  customerOrders: "/studio/customer/orders",
  customerOutfits: "/studio/customer/outfits",
  vendorDashboard: "/studio/vendor",
  adminDashboard: "/studio/admin",
  accessDenied: "/studio/access-denied",
  backendRegistry: "/studio/system/modules",
} as const;
