-- Add missing columns for current Product/Vendor/FavoriteProduct schema
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "stock" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "FavoriteProduct" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "businessName" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "contactPerson" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "county" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "isVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "town" TEXT;
ALTER TABLE "Vendor" ADD COLUMN IF NOT EXISTS "whatsappNumber" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "Vendor_slug_key" ON "Vendor"("slug");
