import { z } from "zod";

export const updateSiteSettingsSchema = z.object({
  body: z.object({
    siteName: z.string().optional().nullable(),
    tagline: z.string().optional().nullable(),
    logoUrl: z.string().optional().nullable(),
    logoDarkUrl: z.string().optional().nullable(),
    faviconUrl: z.string().optional().nullable(),
    heroBannerUrl: z.string().optional().nullable(),
    supportEmail: z.string().optional().nullable(),
    supportPhone: z.string().optional().nullable(),
    whatsappNumber: z.string().optional().nullable(),
    facebook: z.string().optional().nullable(),
    instagram: z.string().optional().nullable(),
    tiktok: z.string().optional().nullable(),
    x: z.string().optional().nullable(),
    linkedin: z.string().optional().nullable(),
    youtube: z.string().optional().nullable(),
    heroTitle: z.string().optional().nullable(),
    heroSubtitle: z.string().optional().nullable(),
    heroCtaText: z.string().optional().nullable(),
    heroCtaLink: z.string().optional().nullable(),
    featuredCategorySlug: z.string().optional().nullable(),
    featuredBrandSlug: z.string().optional().nullable(),
    featuredProductsLimit: z.number().optional().nullable(),
    trendingProductsLimit: z.number().optional().nullable(),
    newArrivalsLimit: z.number().optional().nullable(),
    bestSellersLimit: z.number().optional().nullable(),
    physicalAddress: z.string().optional().nullable(),
    businessHours: z.string().optional().nullable(),
    currency: z.string().optional().nullable(),
    defaultShippingFee: z.number().optional().nullable(),
    aboutUs: z.string().optional().nullable(),
    privacyPolicy: z.string().optional().nullable(),
    termsOfService: z.string().optional().nullable(),
    refundPolicy: z.string().optional().nullable(),
    shippingPolicy: z.string().optional().nullable(),
    siteTitle: z.string().optional().nullable(),
    metaDescription: z.string().optional().nullable(),
    metaKeywords: z.string().optional().nullable(),
    ogImageUrl: z.string().optional().nullable(),
    twitterCardType: z.string().optional().nullable(),
    maintenanceMode: z.boolean().optional().nullable(),
    country: z.string().optional().nullable(),
    language: z.string().optional().nullable(),
  }),
});

export type UpdateSiteSettingsInput = z.infer<typeof updateSiteSettingsSchema>;
